swagger: "2.0"
info:
  title: beego Test API
  description: beego has a very cool tools to autogenerate documents for your API
  version: 1.0.0
  termsOfService: http://beego.me/
  contact:
    email: astaxie@gmail.com
  license:
    name: Apache 2.0
    url: http://www.apache.org/licenses/LICENSE-2.0.html
basePath: /v1
paths:
  /api/user/:
    get:
      tags:
      - api/user
      description: show all cards
      operationId: UserController.showAllCards
      parameters:
      - in: body
        name: body
        description: "true"
        schema:
          $ref: '#/definitions/models.Card'
      responses:
        "200":
          description: Read successfully
        "404":
          description: Fail to read
  /api/user/card:
    post:
      tags:
      - api/user
      description: insert card
      operationId: CardController.Post
  /api/user/card/{id}:
    get:
      tags:
      - api/user
      description: get card
      operationId: CardController.Get
  /api/user/card/help/{Ename}:
    get:
      tags:
      - api/user
      description: get help message by the given enterprise_name
      operationId: CardController.Get
      parameters:
      - in: query
        name: Ename
        description: enterprise_name
        required: true
        type: string
      responses:
        "200":
          description: ""
        "404":
          description: read error
definitions:
  models.Card:
    title: Card
    type: object
    properties:
      BatchNum:
        type: string
      City:
        type: string
      EName:
        type: string
      FactoryNum:
        type: string
      Id:
        type: string
      Kind:
        type: string
      RegisterTime:
        type: string
        format: datetime
      Remark:
        type: string
      SerialNum:
        type: string
      State:
        type: string
      Style:
        type: string
      UserId:
        type: string
