swagger: "2.0"
info:
  title: beego Test API
  description: beego has a very cool tools to autogenerate documents for your API
  version: 1.0.0
  termsOfService: http://beego.me/
  contact:
    email: astaxie@gmail.com
  license:
    name: Apache 2.0
    url: http://www.apache.org/licenses/LICENSE-2.0.html
basePath: /v1
paths:
  /api/user/:
    get:
      tags:
      - api/user
      description: show all cards
      operationId: UserController.showAllCards
      parameters:
      - in: body
        name: body
        description: "true"
        schema:
          $ref: '#/definitions/models.Card'
      responses:
        "200":
          description: Read successfully
        "404":
          description: Fail to read
  /api/user/card:
    post:
      tags:
      - api/user
      description: 插入一张卡片
      operationId: CardController.write by gu yu hao
      parameters:
        - in: body
          name: card
          description: 只需要给出卡Id以及用户Id和备注，即可解析出额外信息
          required: true
          schema:
            $ref: '#/definitions/json{Id:string,UserId:string,Remark:string}'
      responses:
        "200":
          description: 插入卡片成功
        "400":
          description: 解析json错误
        "403":
          description: 插入失败
        "406":
          description: 非法的用户ID
  /api/user/card/{id}:
    get:
      tags:
      - api/user
      description: get card
      operationId: CardController.Get
  /api/user/join:
    post:
      tags:
      - api/user
      description: user register
      operationId: UserController.Register
      parameters:
      - in: user
        name: body
        description: "true"
        schema:
          $ref: '#/definitions/models.User'
      responses:
        "200":
          description: Register successfully
        "400":
          description: Fail to unmarshal json
        "403":
          description: Fail to insert
        "406":
          description: Illegal account form
  /api/user/login:
    put:
      tags:
      - api/user
      description: user login
      operationId: UserController.Login
      responses:
        "200":
          description: Register successfully
        "400":
          description: Fail to unmarshal json
        "404":
          description: Fail to login
definitions:
  json{Id:string,UserId:string,Remark:string}:
    title: json{Id:string,UserId:string,Remark:string}
    type: object
  models.Card:
    title: Card
    type: object
    properties:
      BatchNum:
        type: string
      City:
        type: string
      EName:
        type: string
      FactoryNum:
        type: string
      Id:
        type: string
      Kind:
        type: string
      Remark:
        type: string
      SerialNum:
        type: string
      State:
        type: string
      Style:
        type: string
      UserId:
        type: string
  models.User:
    title: User
    type: object
    properties:
      Id:
        type: string
      Mail:
        type: string
      Password:
        type: string
      Tel:
        type: string
