swagger: "2.0"
info:
  title: beego Test API
  description: beego has a very cool tools to autogenerate documents for your API
  version: 1.0.0
  termsOfService: http://beego.me/
  contact:
    email: astaxie@gmail.com
  license:
    name: Apache 2.0
    url: http://www.apache.org/licenses/LICENSE-2.0.html
paths: {}
definitions:
  models.Card:
    title: Card
    type: object
    properties:
      BatchNum:
        type: string
      City:
        type: string
      EName:
        type: string
      FactoryNum:
        type: string
      Id:
        type: string
      Kind:
        type: string
      Remark:
        type: string
      SerialNum:
        type: string
      State:
        type: string
      Style:
        type: string
      UserId:
        type: string
